"use client";

import { useState } from "react";
import { BookOpenCheck, CalendarDays, Check, Gavel, Plus, ShoppingBag, Star, TicketCheck, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import type { ForumAction, ForumPayload } from "@/lib/forum-store";

type HubTab = "knowledge" | "events" | "market";
const eventStatusLabel: Record<string, string> = { draft: "Черновик", open: "Регистрация открыта", closed: "Регистрация закрыта", completed: "Завершено", cancelled: "Отменено" };
const marketStatusLabel: Record<string, string> = { open: "Открыто", reserved: "Зарезервировано", completed: "Завершено", closed: "Закрыто", disputed: "Спор" };

function has(payload: ForumPayload, permission: string) {
  const user = payload.currentUser;
  return Boolean(user && (["owner", "mrproper"].includes(user.role.id) || user.role.permissions.includes(permission)));
}

export function ForumCommunityHub({ payload, busy, onAction, onLogin }: { payload: ForumPayload; busy: boolean; onAction: (action: ForumAction) => void; onLogin: () => void }) {
  const [tab, setTab] = useState<HubTab>("knowledge");
  const [eventTitle, setEventTitle] = useState(""); const [eventDescription, setEventDescription] = useState(""); const [eventDate, setEventDate] = useState(""); const [eventCapacity, setEventCapacity] = useState(30);
  const [listingType, setListingType] = useState<"sell" | "buy" | "service">("sell"); const [listingTitle, setListingTitle] = useState(""); const [listingDescription, setListingDescription] = useState(""); const [listingPrice, setListingPrice] = useState("");
  return <section className="space-y-5">
    <div className="dark-panel community-hub-head"><div><div className="hero-kicker"><span /> Возможности сообщества</div><h1>Центр CLOUD WORLD</h1><p>Проверенные знания, мероприятия и безопасные игровые сделки.</p></div><div className="community-hub-tabs"><button className={tab === "knowledge" ? "active" : ""} onClick={() => setTab("knowledge")}><BookOpenCheck /> База знаний</button><button className={tab === "events" ? "active" : ""} onClick={() => setTab("events")}><CalendarDays /> События</button><button className={tab === "market" ? "active" : ""} onClick={() => setTab("market")}><ShoppingBag /> Рынок</button></div></div>

    {tab === "knowledge" ? <div className="community-card-grid">{payload.knowledgeArticles.length ? payload.knowledgeArticles.map((article) => <article key={article.id} className="dark-panel community-feature-card"><div className="community-feature-icon"><BookOpenCheck /></div><div><span className="community-eyebrow">Проверено администрацией</span><h2>{article.title}</h2><p className="community-long-text">{article.body}</p><small>{article.authorName} · {new Date(article.updatedAt).toLocaleDateString("ru-RU")}</small></div></article>) : <div className="dark-panel empty-state">Опубликованных статей пока нет. Они появятся из решённых тем после проверки сотрудником.</div>}</div> : null}

    {tab === "events" ? <div className="space-y-4">
      {has(payload, "forum.events.manage") ? <div className="dark-panel community-create-form"><div><div className="hero-kicker"><span /> Панель организатора</div><h2>Новое мероприятие</h2></div><Input value={eventTitle} onChange={(event) => setEventTitle(event.target.value)} placeholder="Название" /><Textarea value={eventDescription} onChange={(event) => setEventDescription(event.target.value)} placeholder="Описание и правила" rows={4} /><div className="grid gap-3 sm:grid-cols-2"><Input type="datetime-local" value={eventDate} onChange={(event) => setEventDate(event.target.value)} /><Input type="number" min={0} max={10000} value={eventCapacity} onChange={(event) => setEventCapacity(Number(event.target.value))} placeholder="Количество мест" /></div><Button disabled={busy || !eventTitle.trim() || !eventDescription.trim() || !eventDate} className="bg-red-600" onClick={() => { onAction({ action: "create_event", title: eventTitle, description: eventDescription, startsAt: eventDate, capacity: eventCapacity }); setEventTitle(""); setEventDescription(""); setEventDate(""); }}><Plus /> Создать событие</Button></div> : null}
      <div className="community-card-grid">{payload.events.map((event) => <article key={event.id} className="dark-panel community-feature-card"><div className="community-feature-icon"><CalendarDays /></div><div><span className="community-eyebrow">{new Date(event.startsAt).toLocaleString("ru-RU")}</span><h2>{event.title}</h2><p>{event.description}</p><div className="community-meta"><span><Users /> {event.registered}{event.capacity ? ` / ${event.capacity}` : ""}</span><span>{eventStatusLabel[event.status] ?? event.status}</span>{event.myStatus ? <span><Check /> {event.myStatus === "registered" ? "Вы участвуете" : event.myStatus === "waitlist" ? "Лист ожидания" : "Регистрация отменена"}</span> : null}</div><div className="community-card-actions">{payload.currentUser ? <Button size="sm" variant="outline" disabled={busy || event.status !== "open"} onClick={() => onAction({ action: "register_event", eventId: event.id })}><TicketCheck /> {event.myStatus === "registered" || event.myStatus === "waitlist" ? "Отменить запись" : "Записаться"}</Button> : <Button size="sm" onClick={onLogin}>Войти для записи</Button>}{has(payload, "forum.events.manage") && event.status === "open" ? <Button size="sm" variant="outline" onClick={() => onAction({ action: "set_event_status", eventId: event.id, status: "closed" })}>Закрыть запись</Button> : null}{has(payload, "forum.events.manage") && !["completed", "cancelled"].includes(event.status) ? <><Button size="sm" onClick={() => onAction({ action: "set_event_status", eventId: event.id, status: "completed" })}><Check /> Завершить</Button><Button size="sm" variant="destructive" onClick={() => onAction({ action: "set_event_status", eventId: event.id, status: "cancelled" })}>Отменить</Button></> : null}</div></div></article>)}</div>
    </div> : null}

    {tab === "market" ? <div className="space-y-4">
      {payload.currentUser ? <div className="dark-panel community-create-form"><div><div className="hero-kicker"><span /> Безопасная торговля</div><h2>Новое объявление</h2></div><div className="grid gap-3 sm:grid-cols-2"><select className="forum-select" value={listingType} onChange={(event) => setListingType(event.target.value as typeof listingType)}><option value="sell">Продам</option><option value="buy">Куплю</option><option value="service">Услуга</option></select><Input value={listingPrice} onChange={(event) => setListingPrice(event.target.value)} placeholder="Цена, например 5000 монет" /></div><Input value={listingTitle} onChange={(event) => setListingTitle(event.target.value)} placeholder="Название объявления" /><Textarea value={listingDescription} onChange={(event) => setListingDescription(event.target.value)} rows={4} placeholder="Подробное описание без паролей и реальных платёжных данных" /><Button disabled={busy || !listingTitle.trim() || !listingDescription.trim() || !listingPrice.trim()} className="bg-red-600" onClick={() => { onAction({ action: "create_market_listing", listingType, title: listingTitle, description: listingDescription, priceLabel: listingPrice }); setListingTitle(""); setListingDescription(""); setListingPrice(""); }}><Plus /> Разместить объявление</Button></div> : null}
      <div className="community-card-grid">{payload.marketListings.map((listing) => <article key={listing.id} className="dark-panel community-feature-card"><div className="community-feature-icon"><ShoppingBag /></div><div><span className="community-eyebrow">{listing.type === "sell" ? "Продажа" : listing.type === "buy" ? "Покупка" : "Услуга"} · {marketStatusLabel[listing.status] ?? listing.status}</span><h2>{listing.title}</h2><p>{listing.description}</p><div className="market-price">{listing.priceLabel}</div><small>Автор: {listing.sellerName}</small><div className="community-card-actions">{payload.currentUser && payload.currentUser.id !== listing.sellerId && listing.status === "open" ? <Button size="sm" className="bg-red-600" disabled={busy} onClick={() => onAction({ action: "reserve_market_listing", listingId: listing.id })}><Gavel /> Начать сделку</Button> : null}{listing.transactionId && listing.transactionStatus === "reserved" && payload.currentUser?.id === listing.sellerId ? <Button size="sm" onClick={() => onAction({ action: "update_market_transaction", transactionId: listing.transactionId!, status: "seller_confirmed" })}><Check /> Подтвердить продавцу</Button> : null}{listing.transactionId && listing.transactionStatus === "seller_confirmed" && payload.currentUser?.id === listing.buyerId ? <Button size="sm" onClick={() => onAction({ action: "update_market_transaction", transactionId: listing.transactionId!, status: "completed" })}><Check /> Товар получен</Button> : null}{listing.transactionId && (payload.currentUser?.id === listing.sellerId || payload.currentUser?.id === listing.buyerId) && !["completed", "cancelled", "disputed"].includes(listing.transactionStatus ?? "") ? <Button size="sm" variant="destructive" onClick={() => onAction({ action: "update_market_transaction", transactionId: listing.transactionId!, status: "disputed" })}><Gavel /> Открыть спор</Button> : null}{listing.transactionId && listing.transactionStatus === "disputed" && has(payload, "forum.market.manage") ? <><Button size="sm" onClick={() => onAction({ action: "update_market_transaction", transactionId: listing.transactionId!, status: "completed" })}><Check /> Закрыть спор</Button><Button size="sm" variant="outline" onClick={() => onAction({ action: "update_market_transaction", transactionId: listing.transactionId!, status: "cancelled" })}>Отменить сделку</Button></> : null}{listing.transactionId && listing.transactionStatus === "completed" && (payload.currentUser?.id === listing.sellerId || payload.currentUser?.id === listing.buyerId) ? <Button size="sm" variant="outline" onClick={() => { const rating = Number(window.prompt("Оценка от 1 до 5", "5")); const body = window.prompt("Короткий отзыв", "Сделка прошла успешно") ?? ""; if (rating) onAction({ action: "review_market_transaction", transactionId: listing.transactionId!, rating, body }); }}><Star /> Оставить отзыв</Button> : null}</div></div></article>)}</div>
    </div> : null}
  </section>;
}
